DROP TABLE upark-data.buildings;
CREATE TABLE upark-data.buildings (bld_id int unsigned NOT NULL, bld_name varchar(128) NOT NULL, bld_longitude decimal(20,16) NOT NULL, bld_lattitude decimal(20,16) NOT NULL, bld_strt_address varchar(64), created_time datetime DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (bld_id), INDEX bld_name_idx (bld_name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 DEFAULT COLLATE=utf8mb3_general_ci;
DROP TABLE upark-data.lot;
CREATE TABLE upark-data.lot (id int unsigned NOT NULL, name varchar(64) NOT NULL, latitude decimal(20,16) NOT NULL, longitude decimal(20,16) NOT NULL, car_count int unsigned DEFAULT 0 NOT NULL, stall_count int unsigned NOT NULL, last_updated datetime, enabled tinyint(1) DEFAULT 1, PRIMARY KEY (id), INDEX lot_name_idx (name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 DEFAULT COLLATE=utf8mb3_general_ci;
DROP TABLE upark-data.lot_snapshots;
CREATE TABLE upark-data.lot_snapshots (snapshot_id int unsigned NOT NULL AUTO_INCREMENT, snapshot_time datetime DEFAULT CURRENT_TIMESTAMP NOT NULL, json_blob blob, PRIMARY KEY (snapshot_id), INDEX lot_snapshot_time_idx (snapshot_time)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 DEFAULT COLLATE=utf8mb3_general_ci;
DROP TABLE upark-data.lots;
CREATE TABLE upark-data.lots (lot_id int unsigned NOT NULL, lot_name varchar(64) NOT NULL, lot_lattitude decimal(20,16) NOT NULL, lot_longitude decimal(20,16) NOT NULL, fullness decimal(16,15) unsigned NOT NULL, car_count int unsigned NOT NULL, stall_count int unsigned NOT NULL, last_updated datetime, PRIMARY KEY (lot_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 DEFAULT COLLATE=utf8mb3_general_ci;
DROP TABLE upark-data.permit;
CREATE TABLE upark-data.permit (id int unsigned NOT NULL, name varchar(8) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 DEFAULT COLLATE=utf8mb3_general_ci;
DROP TABLE upark-data.reports;
CREATE TABLE upark-data.reports (user_id int unsigned NOT NULL, report_id int NOT NULL AUTO_INCREMENT, time datetime DEFAULT CURRENT_TIMESTAMP NOT NULL, lot_id int unsigned NOT NULL, est_fullness decimal(16,15) unsigned NOT NULL, weight int unsigned NOT NULL, PRIMARY KEY (report_id, lot_id, user_id), INDEX fk_report_user_id_idx (user_id), INDEX fk_report_lot_id_idx (lot_id), INDEX lot_fullness_idx (est_fullness)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 DEFAULT COLLATE=utf8mb3_general_ci;
DROP TABLE upark-data.stall;
CREATE TABLE upark-data.stall (lot_id int unsigned NOT NULL, stall_type_id int unsigned NOT NULL, PRIMARY KEY (lot_id, stall_type_id), INDEX fk_stall_stall_type_id (stall_type_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 DEFAULT COLLATE=utf8mb3_general_ci;
DROP TABLE upark-data.stall_type;
CREATE TABLE upark-data.stall_type (id int unsigned NOT NULL, name varchar(8) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 DEFAULT COLLATE=utf8mb3_general_ci;
DROP TABLE upark-data.user;
CREATE TABLE upark-data.user (id char(28) NOT NULL, name varchar(64) NOT NULL, colorblind tinyint(1) DEFAULT 0, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 DEFAULT COLLATE=utf8mb3_general_ci;
DROP TABLE upark-data.user_permit;
CREATE TABLE upark-data.user_permit (user_id char(28) NOT NULL, permit_id int unsigned NOT NULL, PRIMARY KEY (user_id, permit_id), INDEX fk_user_permit_permit_id (permit_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 DEFAULT COLLATE=utf8mb3_general_ci;
DROP TABLE upark-data.users;
CREATE TABLE upark-data.users (user_id int unsigned NOT NULL AUTO_INCREMENT, username varchar(64) NOT NULL, user_fname varchar(64), user_lname varchar(64), created_time datetime DEFAULT CURRENT_TIMESTAMP, last_edited_time datetime, permit varchar(8) DEFAULT 'V', colorblind tinyint DEFAULT 0, PRIMARY KEY (user_id), CONSTRAINT username_UNIQUE UNIQUE (username), INDEX username_idx (username), INDEX user_name_idx (user_lname, user_fname)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 DEFAULT COLLATE=utf8mb3_general_ci;
ALTER TABLE `upark-data`.`reports` ADD CONSTRAINT fk_report_lot_id FOREIGN KEY (`lot_id`) REFERENCES `upark-data`.`lots` (`lot_id`) ;
ALTER TABLE `upark-data`.`reports` ADD CONSTRAINT fk_report_user_id FOREIGN KEY (`user_id`) REFERENCES `upark-data`.`users` (`user_id`);
ALTER TABLE `upark-data`.`stall` ADD CONSTRAINT fk_stall_lot_id FOREIGN KEY (`lot_id`) REFERENCES `upark-data`.`lot` (`id`) ;
ALTER TABLE `upark-data`.`stall` ADD CONSTRAINT fk_stall_stall_type_id FOREIGN KEY (`stall_type_id`) REFERENCES `upark-data`.`stall_type` (`id`);
ALTER TABLE `upark-data`.`user_permit` ADD CONSTRAINT fk_user_permit_permit_id FOREIGN KEY (`permit_id`) REFERENCES `upark-data`.`permit` (`id`) ;
ALTER TABLE `upark-data`.`user_permit` ADD CONSTRAINT fk_user_permit_user_id FOREIGN KEY (`user_id`) REFERENCES `upark-data`.`user` (`id`);
